[package]
name = "my-rest-api"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[profile.release]
opt-level = "z"
codegen-units = 1
strip = true
lto = true

[dependencies]
ntex = { version = "2.1.0", features = ["tokio"] }
serde = { version = "1.0.1", features = ["derive"] }
serde_json = "1.0.96"
utoipa = "4.2.1"
utoipa-swagger-ui = "8.0.0"
env_logger = "0.11.5"
